on:
  push:
    paths:
    - "**/*.js"
  pull_request:
    paths:
    - "**/*.js"

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: npm install, npm run coverage
      run: |
        npm install
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
